spring.application.name=teklify

spring.datasource.url=jdbc:postgresql://localhost:5432/teklify_db
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.profile.active=dev

# Secret key
security.jwt.secret-key=PUBLIC_SECRET_KEY_1234
security.jwt.token-expiration-time=7200000

# Logging Configuration
logging.level.root=WARN
logging.level.com.semihkurucay=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs